name: Daily Branch Creator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Adds manual trigger

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'DouletMedia'
          git config --global user.email 'doulet2023@gmail.com'

      - name: Create new branch
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          git checkout -b $DATE
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} $DATE

      - name: Set branch as default
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d "{\"default_branch\":\"$DATE\"}"

  create-common-file:
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched
          ref: ${{ needs.create-branch.outputs.DATE }}  # Check out the new branch

      - name: Set up Git
        run: |
          git config --global user.name 'DouletMedia'
          git config --global user.email 'doulet2023@gmail.com'

      - name: Create .py file
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          echo "# This is a placeholder Python file" > $DATE.py
          git add $DATE.py
          git commit -m "Add $DATE.py"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:$DATE

      - name: Create .js file
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          echo "# This is a placeholder Python file" > $DATE.js
          git add $DATE.js
          git commit -m "Add $DATE.js"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:$DATE

      - name: Create .bat file
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          echo "# This is a placeholder Python file" > $DATE.bat
          git add $DATE.bat
          git commit -m "Add $DATE.bat"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:$DATE
