name: Daily Branch Creator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create new branch
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          git checkout -b $DATE
          git push origin $DATE

      - name: Set branch as default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d "{\"default_branch\":\"$DATE\"}"
