name: Daily Branch Creator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Adds manual trigger

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Check if branch already exists
        id: check-branch
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          if git show-ref --verify --quiet refs/heads/$DATE; then
            echo "Branch $DATE already exists."
            echo "::set-output name=exists::true"
          else
            echo "Branch $DATE does not exist. Creating branch."
            echo "::set-output name=exists::false"
          fi

      - name: Create new branch if it does not exist
        if: steps.check-branch.outputs.exists == 'false'
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          git checkout -b $DATE

      - name: Push new branch if it was created
        if: steps.check-branch.outputs.exists == 'false'
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          git push origin HEAD:$DATE  # Push the current HEAD to the new branch named $DATE
          
      - name: Set branch as default
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          DATE=$(TZ="America/Toronto" date +'%Y%m%d')
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d "{\"default_branch\":\"$DATE\"}"
